# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Hedgehog Configuration                            ###
###############################################################################

[hedgehog]

# Set the URL we should use for hedgehog 
hedgehog_url = "https://82.208.23.218:39886"